name: 'Example Action'
description: 'Greet someone'

runs:
  using: "composite"
  steps:
    #- uses: actions/setup-node@v3.6.0
    #  with:
    #    node-version: 16
    #- name: Check Node Version
    #  run: node --version
    

    - name: Set Greeting
      run: ${{github.action_path}}
      shell: bash

    - name: Run other.sh
      run: ./${{github.action_path}}/other.sh
      shell: bash

