name: 'Example Action'
description: 'Run a node script'

outputs:
  some-text:
    description: "some text"
    value: ${{ steps.example-run-result.outputs.random-number }}

runs:
  using: "composite"
  steps:
    # also works.
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: node --version
      shell: bash
    - run: node ${{github.action_path}}/index.js
      id: example-run-result
      shell: bash
    


    # - uses: actions/github-script@v7
    #   id: my-script
    #   with:
    #     result-encoding: string
    #     script: |
    #       const component = require("${{github.action_path}}/index.js")
    #       console.log(component.Test())

    #       console.log('string', component['string'])

