name: 'Example Action'
description: 'Greet someone'

runs:
  using: "composite"
  steps:
    #- uses: actions/setup-node@v3.6.0
    #  with:
    #    node-version: 16
    #- name: Check Node Version
    #  run: node --version
    - uses: actions/github-script@v7
      id: my-script
      with:
        result-encoding: string
        script: |
          require("${{github.action_path}}/index.js")

    #- name: Set Greeting
    #  run: echo "${{github.action_path}}"
    #  shell: bash

    #- name: Run other.sh
    #  run: cd ${{github.action_path}} && ./other.sh
    #  shell: bash

